### ISSUE TITLE
Difference between Git and GitHub

### ISSUE THREAD

**Issue by Liyaqatm** [githubschool/cautious-journey#9]
@githubteacher

**Comment by hectorsector** [comment]
Good question, @Liyaqatm! Git is the underlying version control system. GitHub is the social collaboration platform that sits atop of Git. [This portion of the manual](https://githubtraining.github.io/training-manual/02_getting_started.html#what-is-github) may also be helpful!

**Comment by hectorsector** [comment]
@Liyaqatm I think I answered this so I'm going to go ahead and close it -- but feel free to reopen if it didn't cover it.
